version: '3.9'
services:
  db:
    image: postgres:15
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
    restart: on-failure
    ports:
      - ${HTTP_PORT}:8000
    depends_on:
      - db

  nats:
    image: nats-streaming:0.25.6
    restart: on-failure
    command: ["-sc", "/etc/nats-streaming/config.conf"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-streaming-config.conf:/etc/nats-streaming/config.conf

volumes:
  pgdata: