// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderHandlers is a mock of OrderHandlers interface.
type MockOrderHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockOrderHandlersMockRecorder
}

// MockOrderHandlersMockRecorder is the mock recorder for MockOrderHandlers.
type MockOrderHandlersMockRecorder struct {
	mock *MockOrderHandlers
}

// NewMockOrderHandlers creates a new mock instance.
func NewMockOrderHandlers(ctrl *gomock.Controller) *MockOrderHandlers {
	mock := &MockOrderHandlers{ctrl: ctrl}
	mock.recorder = &MockOrderHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderHandlers) EXPECT() *MockOrderHandlersMockRecorder {
	return m.recorder
}

// GetByIdHandler mocks base method.
func (m *MockOrderHandlers) GetByIdHandler(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetByIdHandler", c)
}

// GetByIdHandler indicates an expected call of GetByIdHandler.
func (mr *MockOrderHandlersMockRecorder) GetByIdHandler(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdHandler", reflect.TypeOf((*MockOrderHandlers)(nil).GetByIdHandler), c)
}
