// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go

// Package usecase is a generated GoMock package.
package usecase

import (
	entity "L0/internal/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderInteractor is a mock of OrderInteractor interface.
type MockOrderInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockOrderInteractorMockRecorder
}

// MockOrderInteractorMockRecorder is the mock recorder for MockOrderInteractor.
type MockOrderInteractorMockRecorder struct {
	mock *MockOrderInteractor
}

// NewMockOrderInteractor creates a new mock instance.
func NewMockOrderInteractor(ctrl *gomock.Controller) *MockOrderInteractor {
	mock := &MockOrderInteractor{ctrl: ctrl}
	mock.recorder = &MockOrderInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderInteractor) EXPECT() *MockOrderInteractorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderInteractor) Create(ctx context.Context, order *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderInteractorMockRecorder) Create(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderInteractor)(nil).Create), ctx, order)
}

// Delete mocks base method.
func (m *MockOrderInteractor) Delete(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderInteractorMockRecorder) Delete(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderInteractor)(nil).Delete), ctx, uid)
}

// GetAll mocks base method.
func (m *MockOrderInteractor) GetAll(ctx context.Context) ([]*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrderInteractorMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrderInteractor)(nil).GetAll), ctx)
}

// GetByUid mocks base method.
func (m *MockOrderInteractor) GetByUid(ctx context.Context, uid string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUid", ctx, uid)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUid indicates an expected call of GetByUid.
func (mr *MockOrderInteractorMockRecorder) GetByUid(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUid", reflect.TypeOf((*MockOrderInteractor)(nil).GetByUid), ctx, uid)
}
